name: Gerar APK Android

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Baixar o código
        uses: actions/checkout@v4

      - name: 2️⃣ Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: 3️⃣ Configurar Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: 4️⃣ Instalar pacotes NPM
        run: npm install

      - name: 5️⃣ Construir Projeto Web
        run: npm run build

      - name: Configurar Permissão do Gradle
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          dos2unix android/gradlew
          chmod +x android/gradlew

      - name: 6️⃣ Copiar pro Android (Capacitor)
        run: npx cap sync android

      - name: 7️⃣ Gerar o APK de Release 🏗️
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: 8️⃣ Salvar o APK Final (Release) 📲
        uses: actions/upload-artifact@v4
        with:
          name: Biblia_Catolica_Release
          path: android/app/build/outputs/apk/release/*.apk
